_welcome:
    path:     /
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_profile_show:
    path:      /profile/edit
    defaults:  { _controller: FOSUserBundle:Profile:edit }

fos_user_profile_delete_picture:
    path:      /profile/delete/picture
    defaults:  { _controller: UserBundle:Profile:deletePicture }
    methods:   [DELETE]

fos_user_change_password:
    path:      /profile/changepassword
    defaults:  { _controller: UserBundle:ChangePassword:changePassword }
    methods:   [GET|POST]

fos_ext_avl_user_dashboard_show:
    path:      /profile/dashboard
    defaults:  { _controller: UserBundle:Dashboard:index }

avl_event_show:
    path:      /event
    defaults:  { _controller: UserBundle:Event:index }

avl_enquiry_show:
    path:      /enquiry
    defaults:  { _controller: UserBundle:Enquiry:index }

avl_comment_show:
    path:      /comment
    defaults:  { _controller: UserBundle:Comment:index }