_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

_welcome:
    path:     /
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_profile_show:
    path:      /cnsl/profile/edit
    defaults:  { _controller: FOSUserBundle:Profile:edit }

fos_user_profile_delete_picture:
    path:      /cnsl/profile/remove/picture
    defaults:  { _controller: UserBundle:Profile:removePicture }
    methods:   [DELETE]

fos_user_change_password:
    path:      /cnsl/profile/changepassword
    defaults:  { _controller: UserBundle:ChangePassword:changePassword }
    methods:   [GET|POST]

avl_user_dashboard_show:
    path:      /cnsl/dashboard
    defaults:  { _controller: UserBundle:Dashboard:index }

avl_event_show:
    path:      /cnsl/event
    defaults:  { _controller: UserBundle:Event:index }

avl_comment_show:
    path:      /cnsl/comment
    defaults:  { _controller: UserBundle:Comment:index }

avl_subuser:
    path:      /cnsl/subuser
    defaults:  { _controller: UserBundle:SubUser:index }

avl_subuser_new:
    path:      /cnsl/subuser/new
    defaults:  { _controller: UserBundle:SubUser:new }

avl_subuser_edit:
    path:      /cnsl/subuser/edit/{id}
    defaults:  { _controller: UserBundle:SubUser:edit }

avl_subuser_remove:
    path:      /cnsl/subuser/remove/{id}
    defaults:  { _controller: UserBundle:SubUser:remove }
    requirements:
        _method: DELETE

avl_subuser_switch_on:
    path:      /cnsl/subuser/switch-on
    defaults:  { _controller: UserBundle:SubUser:switchon }

avl_subuser_switch_off:
    path:      /cnsl/subuser/switch-off
    defaults:  { _controller: UserBundle:SubUser:switchoff }

avl_content_show:
    path:      /cnsl/content/{slug}
    defaults:  { _controller: UserBundle:Content:index }
    requirements:
        _method: GET

avl_faq_enquiry:
    path:      /cnsl/faq/enquiry
    defaults:  { _controller: UserBundle:Enquiry:enquiry }
    requirements:
        _method:  GET|POST

###
# All for admin
##
