_welcome:
    path:     /
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_profile_show:
    path:      /profile/edit
    defaults:  { _controller: FOSUserBundle:Profile:edit }

fos_user_profile_delete_picture:
    path:      /profile/delete/picture
    defaults:  { _controller: UserBundle:Profile:deletePicture }
    methods:   [DELETE]

fos_ext_avl_user_dashboard_show:
    path:      /profile/dashboard
    defaults:  { _controller: UserBundle:Dashboard:index }