security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_CUSTOMER_EVENT_MANAGER: ROLE_USER
        ROLE_CUSTOMER_COMMENT_MANAGER: ROLE_USER
        ROLE_CUSTOMER_SUBUSER_MANAGER: ROLE_USER
        ROLE_CUSTOMER_FBC_MANAGER: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            switch_user: { role: ROLE_ADMIN, parameter: switch }
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider

                login_path: /login
                check_path: /login_check

                always_use_default_target_path: false
                default_target_path: avl_user_dashboard_show
                use_forward: true
                use_referer: false
            logout:
                path:   /logout
                target: /login
            anonymous:    true
    access_control:
        - { path: ^/(login|register|resetting)$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(cnsl/event.*)$, role: ROLE_CUSTOMER_EVENT_MANAGER }
        - { path: ^/(cnsl/comment.*)$, role: ROLE_CUSTOMER_COMMENT_MANAGER }
        - { path: ^/(cnsl/dashboard|cnsl/content.*|cnsl/news.*|cnsl/switch-on|cnsl/switch-switch-off)$, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/(cnsl/subuser.*)$, role: [ROLE_ADMIN, ROLE_CUSTOMER_SUBUSER_MANAGER] }
        - { path: ^/(cnsl/subuser.*|cnsl/profile/fbc/.*)$, role: [ROLE_ADMIN, ROLE_CUSTOMER_FBC_MANAGER] }
        - { path: ^/(cnsl/admin/news.*|cnsl/admin/faq.*)$, role: ROLE_ADMIN }
