services:
    app.locale_listener:
        class: Avl\UserBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
    avl_user.profile.form.type:
        class: Avl\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: avl_user_profile }
    avl_user.registration.form.type:
            class: Avl\UserBundle\Form\Type\RegistrationFormType
            tags:
                - { name: form.type, alias: avl_user_registration }
    avl_user.changepassword.form.type:
                class: Avl\UserBundle\Form\Type\ChangePasswordFormType
                tags:
                    - { name: form.type, alias: avl_user_change_password }
    avl_user.profile_edit:
        class: Avl\UserBundle\EventListener\ProfileEditListener
        arguments: [@router, @service_container]
        tags:
            - { name: kernel.event_subscriber }
    avl_user.change_password:
            class: Avl\UserBundle\EventListener\ChangePasswordListener
            arguments: [@router, @service_container]
            tags:
                - { name: kernel.event_subscriber }
    avl_user.registration:
            class: Avl\UserBundle\EventListener\RegistrationListener
            arguments: [@router, @service_container]
            tags:
                - { name: kernel.event_subscriber }
    avl_user.login_manager:
        class: Avl\UserBundle\EventListener\LoginListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }
    avl.twig.extension.UserProfileImagePath:
         class: Avl\UserBundle\Twig\Extension\UserProfileImagePathExtension
         arguments: [@service_container]
         tags:
            - { name: twig.extension }
    image_service:
             class: Common\Services\ImageService
             arguments: []
             tags:
                - { name: image.service }

    avl_user.profile.form.factory:
        class: Avl\UserBundle\Form\Factory\FormFactory
        arguments: ["@form.factory", "%fos_user.profile.form.name%", "%fos_user.profile.form.type%", "%fos_user.profile.form.validation_groups%"]